### ISSUE TITLE
React-Bootstrap components don't handle onClick

### ISSUE THREAD

**Issue by madisvain** [react-bootstrap/react-router-bootstrap#112]
So after https://github.com/react-bootstrap/react-bootstrap/pull/1096 got merged I think the react-router-boostrap MenuItemLink is still broken.

What and how should be done about it? If somebody could give me a clue maybe I could help put together a fix for this.

Related also to:
https://github.com/react-bootstrap/react-router-bootstrap/issues/24
https://github.com/react-bootstrap/react-bootstrap/issues/526

**Comment by mtscout6** [comment]
I'm foggy about the details, but essentially you should be able to tap into the new event structure from the Dropdown button and tell it to prevent default without preventing the selection. Then it will collapse as you expect. I haven't had the time to update this library since that change but a PR to update this would be much appreciated. Let me know if you need help with specifics and I'll carve up so time to dig in a little bit.

**Comment by barrystaes** [comment]
I dont understand/find how to hook into the event system. 

The menu we have has this structure: `<NavBar><CollapsibleNav><Nav><DropdownButton><MenuItem>...` and it wont hide/collapse, not when clicking outside of it, and not when clicking an item.

**Comment by taion** [comment]
@mtscout6 I think the issue here might be that `MenuItem` ignores the `onClick` prop.

**Comment by jquense** [comment]
Ya I was going to fix that... it really should chain them, an annoying oversight

**Comment by jchapple** [comment]
FYI, a yucky, imperative, non-jQuery hack to get the nav to collapse when items are clicked:

```javascript
  componentDidMount() {
    // Temporary workaround for closing CollapsibleNav when items are clicked,
    // see: https://github.com/react-bootstrap/react-router-bootstrap/issues/112
    const navBar = React.findDOMNode(this).querySelector('nav.navbar');
    const collapsibleNav = navBar.querySelector('div.navbar-collapse');
    const btnToggle = navBar.querySelector('button.navbar-toggle');

    navBar.addEventListener('click', (evt) => {
      if (evt.target.tagName !== 'A' || evt.target.classList.contains('dropdown-toggle') || ! collapsibleNav.classList.contains('in')) {
        return;
      }

      btnToggle.click();
    }, false);
  }
```

:scream:

**Comment by jchapple** [comment]
I tried this horrible, imperative workaround to try to get the menu to collapse when items within the list are clicked. Works well on desktop but doesn't seem to work on mobile/touch for me. It seems that `.click()` doesn't click the toggle button as desired, but this could be because I'm using [fastclick](https://github.com/ftlabs/fastclick) - not too sure right now.

```javascript
componentDidMount() {
  const navBar = React.findDOMNode(this).querySelector('nav.navbar');
  const collapsibleNav = navBar.querySelector('div.navbar-collapse');
  const btnToggle = navBar.querySelector('button.navbar-toggle');

  navBar.addEventListener('click', (evt) => {
    if (evt.target.tagName !== 'A' || evt.target.classList.contains('dropdown-toggle') || ! collapsibleNav.classList.contains('in')) {
      return;
    }

    btnToggle.click();
  }, false);
}
```

FYI - I'm also experiencing problems with `MenuItem` wrapped with `LinkContainer` - the links are not intercepted by `react-router`, and instead the browser natively handles the link .

**Comment by barrystaes** [comment]
Thanks @jchapple those insights are much appreciated!
I'll look into this (no fastclick) and update this comment within a day.

**Comment by barrystaes** [comment]
Thanks @jchapple those insights are much appreciated!
I tried your workaround (not using fastclick) and it works on desktop. :+1: 

Observations:
 - Does NOT work when clicking the text or icon `span`, but does work when clicking elsewhere in the item row.
 - Works OK with a `<DropdownButton>` in the menu. A click expands it, and an item click collapses the  whole navbar again.
 - Identical behavior on mobile (tested two Android 4 devices with Chrome)
 - In my case `React.findDOMNode(this)` already returns the `nav.navbar` and in that case `.querySelector('nav.navbar')` returns `null`.

**Comment by taion** [comment]
Affected components:
- MenuItem
- NavItem

**Comment by jchapple** [comment]
With the latest fixes in https://github.com/react-bootstrap/react-bootstrap/pull/1414, I've been able to get the menu to collapse when items are selected by doing something like:

```javascript
import React, { Component, PropTypes } from 'react';
import { Button, Navbar, Nav, CollapsibleNav, NavItem, NavDropdown, NavBrand, MenuItem } from 'react-bootstrap';
import { LinkContainer } from 'react-router-bootstrap';

class Header extends Component {

  static propTypes = {
    flux: PropTypes.object.isRequired,
    authStore: PropTypes.object.isRequired
  }

  state = {
    navExpanded: false
  }

  onNavItemClick = () => {
    this.setState({ navExpanded: false });
  }

  onNavbarToggle = () => {
    this.setState({ navExpanded: ! this.state.navExpanded });
  }

  render() {
    const isAuthenticated = Boolean(this.props.authStore.toJS().token);

    const navCollapsible = (
      <CollapsibleNav eventKey={ 0 }>
        <Nav navbar>
          <NavDropdown eventKey={ 1 } title='Numbering' id='collapsible-nav-dropdown-numbering'>
            <LinkContainer to='/numbers/allocations'><MenuItem onClick={ this.onNavItemClick } eventKey={ 1 }>Allocations</MenuItem></LinkContainer>
            <LinkContainer to='/numbers/ranges'><MenuItem onClick={ this.onNavItemClick } eventKey={ 2 }>Ranges</MenuItem></LinkContainer>
          </NavDropdown>
          <LinkContainer to='/routes'><NavItem onClick={ this.onNavItemClick } eventKey={ 2 }>Routing</NavItem></LinkContainer>
          <LinkContainer to='/sims'><NavItem onClick={ this.onNavItemClick } eventKey={ 3 }>SIMs</NavItem></LinkContainer>
          <LinkContainer to='/customers'><NavItem onClick={ this.onNavItemClick } eventKey={ 4 }>Customers</NavItem></LinkContainer>
          <LinkContainer to='/logs'><NavItem onClick={ this.onNavItemClick } eventKey={ 5 }>Logs</NavItem></LinkContainer>
        </Nav>
        <Nav navbar right>
          <NavItem eventKey={ 1 } onClick={ this.onNavItemClick } href='#'>Sign Out</NavItem>
        </Nav>
      </CollapsibleNav>
    );

    return (
      <div>
        <header className='app--header'>
          <Navbar toggleNavKey={ isAuthenticated ? 0 : null } navExpanded={ this.state.navExpanded } onToggle={ this.onNavbarToggle } staticTop>
            <NavBrand><LinkContainer to='/'><Button bsStyle='link'>Core Manager</Button></LinkContainer></NavBrand>
            { isAuthenticated ? navCollapsible : null }
          </Navbar>
        </header>
      </div>
    );
  }
}

export default Header;

```

Note the `onToggle` handler on `Navbar` and the binding of `navExpanded` to `this.state` so that it can be toggled within the component.

Obviously the duplicated `onClick` handlers for all instances of `NavItem` / `MenuItem` isn't great but I guess ideally this would behaviour would be baked directly into `react-bootstrap` as an option?

**Comment by taion** [comment]
At some point. That's not really related to this issue though.
