### ISSUE TITLE
optionally add active prop

### ISSUE THREAD

**Issue by BerkeleyTrue** [react-bootstrap/react-router-bootstrap#134]
We would like to have better control over whether the active class is added to a NavItem in the LinkContainer component. Right now that's not possible because cloneElement will override our props set on the child.

react-router now has logic to let the user choose the active className property and I would like to replicate that logic for the LinkContainer.

**Comment by taion** [comment]
Can we just make `childProps.active` take precedence when specified?

**Comment by BerkeleyTrue** [comment]
That should work. As long as active={ false } is honored.

**Comment by taion** [comment]
My preference would be to check in order:

1. `this.props.active`
2. `child.props.active`
3. `history.isActive(...)`

Any chance you have time to put together a PR?

**Comment by BerkeleyTrue** [comment]
Will do. Are we ignoring active if it is null or undefined?

**Comment by taion** [comment]
Right, exactly - take `active` from (1) or (2) if they're non-null-y.

**Comment by taion** [comment]
@BerkeleyTrue Any update?

**Comment by cwbuecheler** [comment]
I have a setup with a Navbar. eg:

Dashboard | About Us | Contact

Where the "Dashboard" section then has a sidebar with sub-navigation. But my routes are not sub-routes of /dashboard. As a result, the "Dashboard" item in the menu is only active when the path is "/dashboard" and not, for example, when it's "/devices" ... I know there's an argument to be made that this is not the best setup, but we really don't want everything living under /dashboard.

It looks like a solution to this issue would help me as well, since I could just override the default behavior with props. I might take a stab at a PR.

**Comment by taion** [comment]
Use `<IndexRoute>`s for that; RR is more than flexible enough to allow that pattern.

**Comment by BerkeleyTrue** [comment]
@taion Apologies, but I've not had a chance to implement this feature. Shortly before submitting this issue I created a fork version that we have been using every since.

**Comment by taion** [comment]
No worries.

**Comment by cwbuecheler** [comment]
@taion - thanks, I'll look into `<IndexRoute>`
