### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by gurkerl83** [react-bootstrap/react-router-bootstrap#249]
Is it possible to publish a new release which includes the context-fix anytime soon to npm, thx.

**Comment by kfitzgerald** [comment]
I'm guessing this may need a major rev bump, since the module now exports a wrapped component instead of the original component. The docs may need some love to show this as well.

For example:
```js
// with imports:
import LinkContainer from 'react-router-bootstrap'; // wrapped LinkContainer component
import { LinkContainer as UnwrappedLinkContainer } from 'react-router-bootstrap/lib/LinkContainer'; // original component

// with require
const LinkContainer = require('react-router-bootstrap').LinkContainer;
const UnwrappedLinkContainer = require('react-router-bootstrap/lib/LinkContainer').LinkContainer;
```

Anyone who implemented custom components extending LinkContainer may be in for a surprise.  The unwrapped component is still accessible, but a bit cumbersome to get at if someone wanted to wrap it themselves. Could consider exporting it in `index` as `UnwrappedLinkContainer` or something to that effect.

/cc @v12

**Comment by meetajhu** [comment]
Even i have the same problem with React Router v4.4.0+

**Comment by v12** [comment]
Thanks all for your contributions! New version (0.25.0) has been published and should resolve your issues. I'll  update readme and changelog to include details about the changes.
