### ISSUE TITLE
LinkContainer don`t like spaces?

### ISSUE THREAD

**Issue by artygrand** [react-bootstrap/react-router-bootstrap#258]
I spent much time to understand why my app crash without any error (just white screen unlike in codesandbox) after click on NavDropdown

https://codesandbox.io/s/green-worker-o8x53?file=/src/App.js

It is as planned?

**Comment by bpas247** [comment]
this is because
```jsx
<LinkContainer to="/profile">
  <NavDropdown.Item>Profile</NavDropdown.Item>
</LinkContainer>
```
gets transpiled to
```js
React.createElement(
  LinkContainer,
  {
    to: "/profile",
  },
  React.createElement(NavDropdown.Item, null, "Profile")
);
```
whereas
```jsx
<LinkContainer to="/profile">
  <NavDropdown.Item>Profile</NavDropdown.Item>{" "}
</LinkContainer>
```
gets transpiled to 
```js
React.createElement(
  LinkContainer,
  {
    to: "/profile",
  },
  React.createElement(NavDropdown.Item, null, "Profile"),
  " "
);
```
which is now passing two elements as the `children` (simple example shown [here](https://codesandbox.io/s/additional-space-being-passed-as-children-example-e2n7j?file=/src/App.js)) to the `LinkContainer` component (causing the [assertion](https://github.com/react-bootstrap/react-router-bootstrap/blob/192f75f7ec6e46827d43a86cdc643ac21d7d80e9/src/LinkContainer.js#L92) to throw an exception).

I would say this is expected behavior, so I'm not sure if there's anything we can do on our end about it

**Comment by artygrand** [comment]
But code is
`<LinkContainer to="/profile"><NavDropdown.Item>Profile</NavDropdown.Item> </LinkContainer>`
not
`<LinkContainer to="/profile">
  <NavDropdown.Item>Profile</NavDropdown.Item>{" "}
</LinkContainer>`

so ok
